services:
  - type: web
    name: rasa-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirement.txt
    startCommand: |
      bash start.sh
    envVars:
      - key: PORT
        value: 5005
