services:
  - type: web
    name: rasa-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      rasa train
    startCommand: cd backend && rasa run --enable-api --cors "*" --debug
    autoDeploy: true
    region: oregon
    branch: main
    repo: https://github.com/SahilB2k/RASA_Portfolio
